version: '3'

services:
  wordpress:
    build: .
    ports:
    - '8080:80'
    volumes:
     - ./:/var/www/html/wp-content/plugins/kickgogo/
  
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
    - data-volume:/var/lib/mysql

volumes:
  data-volume:
